name:                hotswap-test
version:             0.1.0.0
github:              "githubuser/hotswap-test"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hotswap-test#readme>

dependencies:
- base >= 4.7 && < 5
- concurrent-extra
- ghci
- deepseq
- text


library:
  source-dirs: src

executables:
  hotswap-test-exe:
    main:                Main.hs
    source-dirs:         app
    c-sources: app/Main.c
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -rdynamic
    - -fwhole-archive-hs-libs
    - -no-hs-main
    dependencies:
    - hotswap-test
